CREATE TABLE IF NOT EXISTS lsf_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    topic VARCHAR(255) NOT NULL,
    msg_key VARCHAR(255) NULL,

    event_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(200) NOT NULL,
    correlation_id VARCHAR(100) NULL,
    aggregate_id VARCHAR(100) NULL,

    envelope_json JSONB NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ NULL,
    retry_count INT NOT NULL DEFAULT 0,
    last_error TEXT NULL,

    lease_owner VARCHAR(128) NULL,
    lease_until TIMESTAMPTZ NULL,
    next_attempt_at TIMESTAMPTZ NULL
    );

CREATE UNIQUE INDEX IF NOT EXISTS uk_lsf_outbox_event_id ON lsf_outbox(event_id);
CREATE INDEX IF NOT EXISTS idx_lsf_outbox_status_created ON lsf_outbox(status, created_at);
CREATE INDEX IF NOT EXISTS idx_lsf_outbox_lease ON lsf_outbox(status, lease_until);
CREATE INDEX IF NOT EXISTS idx_lsf_outbox_next_attempt ON lsf_outbox(status, next_attempt_at);